// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfpbqpjmhkqjojxcneiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mcGJxcGptaGtxam9qeGNuZWl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MDE3ODIsImV4cCI6MjA2NTA3Nzc4Mn0.88RWjOjAbTAqnMoimI76LlbcRxqwWXGwHjMi8uKtKhI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);